### ISSUE TITLE
Descendants with matching field(s)

### ISSUE THREAD

**Issue by gevezex** [matthiask/django-tree-queries#10]
Hi,

Just testing this beautiful library. Was wondering if requesting for de descendants() it is also possible to request the descendants with only matching fields. Or should I do that with a list comprehension on every descendant object? Can imagine that would be multiple queries what would be pitty.

**Comment by matthiask** [comment]
What do you mean with "matching fields"?

`.descendants()` returns a queryset, you can absolutely add additional `.filter()` statements etc. at the end. (If it doesn't work please report a bug!)

**Comment by gevezex** [comment]
Didn't know it was giving back a queryset. That was exactly what I was looking for. Thnx!
