### ISSUE TITLE
Swap out tox for nox this should offer a better test isolation and matrix testing 

### ISSUE THREAD

**Issue by jackton1** [matthiask/django-tree-queries#2]
@matthiask Based on this comment `'maybe also MySQL 8.0 but I found no easy way to test against it.'`

Was there any issue regarding the test setup that made this difficult. 

https://nox.thea.codes/en/stable/

**Comment by matthiask** [comment]
Hi @jackton1 

I'm quite happy with tox, and I don't really want to run matrix tests locally, not even with the help of pyenv and friends. I run only one test locally and then I let Travis CI do the rest.

The comment in the README should mention that I haven't found an easy way to install newer MySQL versions on Travis CI. (I should mention that I haven't spent much time searching for a solution though.)
