### ISSUE TITLE
Is there a recommended way to get a tree's leaf nodes? 

### ISSUE THREAD

**Issue by peter-stuart-turner** [matthiask/django-tree-queries#25]
Should this be done using sorting? Sorry am still a bit new to tree-type structures in SQL

**Comment by matthiask** [comment]
Hey,

So, leaf nodes are nodes which never appear as a parent of another node. You should be able to fetch leaf nodes as follows:

`TreeNode.objects.exclude(id__in=TreeNode.objects.values("parent"))`

or maybe the following if you need the `tree_depth`, `tree_path` etc. fields:

`TreeNode.objects.with_tree_fields().exclude(id__in=TreeNode.objects.values("parent"))`

**Comment by peter-stuart-turner** [comment]
Thanks! And for the library

**Comment by freder** [comment]
isn't it easier to just say 'leaf nodes are nodes that have no children'?

```python
class Model(TreeNode):
	# [...]
	parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE, related_name='children')

def getLeafNodes():
	return Model.objects.filter(children=None)
```

**Comment by matthiask** [comment]
Yeah, this works too. 

My version uses a subquery, yours an outer join. My version is (much!) longer but it is closer to what I would write if I were to write the SQL by hand; I have no idea which version performs better (under which circumstances) but whatever works :) 

I'm just not that comfortable with `many=None` type filtering in Django's ORM but I couldn't explain why.
