### ISSUE TITLE
How to serialize a subtree?

### ISSUE THREAD

**Issue by jet10000** [matthiask/django-tree-queries#30]
follow this thread https://github.com/matthiask/django-tree-queries/issues/27 , it's only serialize whole tree, How to serialize a subtree?

**Comment by matthiask** [comment]
Here's an example how to fetch a node and all descendants: https://github.com/matthiask/django-tree-queries/blob/b6dd583fad6983533da984caab157096008fd38e/tests/testapp/test_queries.py#L85-L88

**Comment by jet10000** [comment]
But, How to serialize it , #27 read children(None) , but descendants read children(None) is empty, I tested it and didn't get it.

**Comment by matthiask** [comment]
```python
children = defaultdict(list)
parent = FzFolder.objects.get(pk=1)
for node in parent.descendants():
    children[node.parent].append(node)
roots = [self.serialize(root, children) for root in children[parent]]
```

I don't know why you're accessing `node.parent.parent`, I don't think that's correct.

Since you're interested in the descendants of the node with PK 1 you should start there and not from the roots of the tree (parent `None`)
