### ISSUE TITLE
Is there a good way to access tree_depth on a single node/object? 

### ISSUE THREAD

**Issue by peter-stuart-turner** [matthiask/django-tree-queries#31]
I am having to use the queryset method:

TreeNode.objects.filter(id=node.id).with_tree_fields().first().tree_depth

but is there an easier way to access - I am wanting to serialize it within Django Rest framework

**Comment by matthiask** [comment]
Hi

There's no easier way to know the position of the node in the tree without building the whole tree structure in the database. Not without denormalization.

**Comment by peter-stuart-turner** [comment]
Got it, thanks

**Comment by matthiask** [comment]
Sorry, what I wrote above isn't completely correct. A simpler recursive CTE for fetching the depth is possible of course but django-tree-queries doesn't have any support for this. 

Thanks!
