### ISSUE TITLE
How to change sibling order when querying a tree?

### ISSUE THREAD

**Issue by rhomboss** [matthiask/django-tree-queries#33]
Hi,

When querying a tree is it possible to order siblings in the tree using a field other than the one defined in the tree model's meta ordering field?

Thanks!

**Comment by matthiask** [comment]
Hi

Yes, that's (somewhat) supported. You have to use `.extra()` though. Here's an example: https://github.com/matthiask/django-tree-queries/blob/bc06562039b88cf696c16573abd527fe219bfdd6/tests/testapp/test_queries.py#L226-L241

I'd definitely accept a pull request making this easier (or documenting this).

**Comment by matthiask** [comment]
Oh, sorry. No, you want to order **siblings** differently. No, that's currently impossible. The field which defines ordering among siblings is selected here: https://github.com/matthiask/django-tree-queries/blob/bc06562039b88cf696c16573abd527fe219bfdd6/tree_queries/compiler.py#L137

I have no good idea for an API which would allow overriding this. What's the use case? I can imagine that this makes sense. OTOH, I use django-tree-queries to replace django-mptt which doesn't allow ordering siblings *in a single query* differently.

**Comment by rhomboss** [comment]
Thanks for the response!

My use case is a tree that can sort siblings either by their name string or creation date.

After reviewing the compiler code where sibling order is defined I put the following quick and dirty solution together.

I added the following method to `TreeQuerySet` to add a `sibling_order` attribute to queries:
```python
def order_siblings_by(self, order_by):
        """
            Sets a query attribute to order siblings with
        """
        self.query.__class__ = TreeQuery
        self.query.sibling_order = order_by
        return self
```

And I modified the if statement that controls sibling ordering to check for the `sibling_order` attribute:
```python
"order_by": self.query.sibling_order[0] if hasattr(self.query, 'sibling_order') else opts.ordering[0] if opts.ordering else opts.pk.attname,
```

With these changes you can specify an alternative sibling ordering by calling the `order_siblings_by` method like so:
```python
Tree.objects.order_siblings_by(order_by=['alternateField'])
```

I'm not sure if this is the best way of doing this but based on my limited testing it works.

**Comment by matthiask** [comment]
Ah yes, that seems like it should work. I'm wondering though... is the new `sibling_order` preserved even when calling e.g. `Tree.objects.order_siblings_by(order_by=['alternateField']).all()` (cloning the query once more?). Is there a way to initialize `sibling_order` earlier, e.g. in an overridden `__init__` method so that the additional complexity isn't hidden inside the compiler?

**Comment by rhomboss** [comment]
I agree with your concerns so I did a little digging around in [Django's source](https://github.com/django/django/blob/c8459708a7e0a2474255b77d0f104a7f16e8b32c/django/db/models/sql/subqueries.py#L53-L64) and came up with the following solution which exposes `sibling_order` better and handles your cloning properly.

We can add the following `__init__` and `_setup_query` methods to `TreeQuery` to initialize a `sibling_order` attribute and implement the default sibling ordering behavior that was previously housed in the `as_sql` method of `TreeCompiler`.
```python
def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._setup_query()

def _setup_query(self):
        """
        Run on initialization and at the end of chaining. Any attributes that
        would normally be set in __init__() should go here instead.
        """
        # Only add the sibling_order attribute if the query doesn't already have one to preserve chaining behavior
        if not hasattr(self, 'sibling_order'):
            # Add an attribute to control the ordering of siblings within trees
            self.sibling_order = self.model._meta.ordering[0] if self.model._meta.ordering else self.model._meta.pk.attname

```

Since the `sibling_order` attribute has been initialized we can simplify the `TreeCompiler`'s `as_sql` method like so:
```python
"order_by": self.query.sibling_order,
```

We then have to modify `with_tree_fields` and `order_siblings_by` to properly initialize `TreeQuery`.
```python
def with_tree_fields(self, tree_fields=True):
        """
        Requests tree fields on this queryset

        Pass ``False`` to revert to a queryset without tree fields.
        """
        if tree_fields:
            self.query.__class__ = TreeQuery 
            self.query._setup_query()
        else:
            self.query.__class__ = Query
        return self

def order_siblings_by(self, order_by):
        """
        Sets TreeQuery sibling_order attribute
        """
        self.query.__class__ = TreeQuery
        self.query._setup_query()
        self.query.sibling_order = order_by[0]
        return self
```

Now cloning is handled properly so `Tree.objects.order_siblings_by(order_by=['alternateField']).all()` works.

I limited sibling ordering to using only a single model field because that's what your original code appeared to do. Is there a reason for this?

**Comment by matthiask** [comment]
Nice! this does look good.

The reasons for using a single model field were that it's easier this way and that we can use a PostgreSQL array when ordering by an integer field instead of stringifying the tree ordering (as we have to do otherwise or when using another database)

**Comment by matthiask** [comment]
> If you’d like, I can put this code together into a pull request along with an appropriate test to add sibling ordering functionality to django-tree-queries. Otherwise I think we can consider this issue closed.

Sure, that would be great! If you find the time.

**Comment by rhomboss** [comment]
Happy to help!
