### ISSUE TITLE
No attribute _with_tree_fields with ManyToManyRelation

### ISSUE THREAD

**Issue by sacovo** [matthiask/django-tree-queries#5]
If using a ManyToManyRelation with a model that is a TreeNode I get an error if I try to access the related set on the other model if I use version >= 0.4.1.

```Python
'ManyRelatedManager' object has no attribute '_with_tree_fields'
```
Setting the `base_manager_name` to use a TreeManager doesn't help either, because the Manager is not initialized through `TreeQuerySet.as_manager()` and thus the field is not there either. One way to fix it would be if the get_queryset Method of the TreeManager would use `getattr` instead of accessing the attribute directly.

```Python
return queryset.with_tree_fields() if getattr(self, '_with_tree_fields', False) else queryset
```

This way the related-manager would work, but not have the the tree fields by default.

**Comment by matthiask** [comment]
Thank you for the report! I think I found a way to make tree fields available by default on relations too. 

Could you try whether `django-tree-queries==0.4.3` fixes the issue? Thanks!

**Comment by sacovo** [comment]
yes, it works, thanks!
