### ISSUE TITLE
Greate idea but proper documentation is needed

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [matthiask/django-tree-queries#7]
I dont understand how to use it. Please add some docs with examples

**Comment by matthiask** [comment]
Thanks for the report. You're right, the documentation is bad right now. In the meantime, I hope the following links help get you up to speed:

Here are a few examples: https://feincms3.readthedocs.io/en/latest/guides/navigation.html

The testsuite has a few examples too https://github.com/matthiask/django-tree-queries/blob/master/tests/testapp/test_queries.py

**Comment by matthiask** [comment]
I think I'll count this as fixed now that the README has a Recipes section.

https://github.com/matthiask/django-tree-queries#recipes
