### ISSUE TITLE
Children only

### ISSUE THREAD

**Issue by gevezex** [matthiask/django-tree-queries#9]
How can I get only the children instead of all the decsendants?

**Comment by matthiask** [comment]
Hey @gevezex 

Use `node.children.all()`, or whatever the [`related_name` value of your model is](https://github.com/matthiask/django-tree-queries/blob/74ad3cb89fd61cfb6a05dd82f6ce5738afd1081f/tree_queries/models.py#L18).

This isn't specific to django-tree-queries; just use Django's related manager for this.

I hope this helps :)

**Comment by gevezex** [comment]
Thnx! And also thnx for this great library 👏🏼

**Comment by matthiask** [comment]
Thank you! You're welcome :)
